import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import pageLayoutStyles from '../styles/pageLayout.module.scss';
import './globals.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Task App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
  children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div className={pageLayoutStyles.pageLayoutContainer}>
					{children}
				</div>
			</body>
		</html>
	);
}
